#ifndef ROS_LOADER_MAIR_H
#define ROS_LOADER_MAIR_H

#define __MAIR_TRANSIENT 0x8
#define __MAIR_WRITE_BACK 0x4
#define __MAIR_READ_ALLOCATE 0x2
#define __MAIR_WRITE_ALLOCATE 0x1

#define _MAIR_DEVICE_nGnRE 0x4
#define _MAIR_NON_CACHEABLE 0x4
#define _MAIR_CACHEABLE ((unsigned long long)(__MAIR_TRANSIENT | __MAIR_WRITE_BACK | __MAIR_READ_ALLOCATE | __MAIR_WRITE_ALLOCATE))

#define MAIR_DEVICE _MAIR_DEVICE_nGnRE
#define MAIR_CACHEABLE (_MAIR_CACHEABLE | (_MAIR_CACHEABLE << 4))
#define MAIR_NON_CACHEABLE (_MAIR_NON_CACHEABLE | (_MAIR_NON_CACHEABLE << 4))

#define MAIR_DEVICE_INDEX 0
#define MAIR_CACHEABLE_INDEX 1
#define MAIR_NON_CACHEABLE_INDEX 2

#endif
